apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: kube-system

images:
  - name: csi-arca-storage
    newName: csi-arca-storage
    newTag: dev  # Use local dev build

configMapGenerator:
  - name: csi-arca-storage-config
    behavior: replace
    files:
      - config.yaml

secretGenerator:
  - name: csi-arca-storage-secret
    literals:
      - auth-token=dev-token

commonLabels:
  environment: development
